"""fix foreignkey definition field track_id table TrackStreamDay

Revision ID: 230c5f96c628
Revises: 45380f93f7cc
Create Date: 2025-07-21 09:50:19.784145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '230c5f96c628'
down_revision: Union[str, Sequence[str], None] = '45380f93f7cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
