"""Update some tiny modifications

Revision ID: 448246aa6331
Revises: 998030cba0da
Create Date: 2025-07-06 10:31:50.854274

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "448246aa6331"
down_revision: Union[str, Sequence[str], None] = "998030cba0da"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "artist", ["spotify_id"])
    op.create_unique_constraint(None, "spotify_track", ["spotify_id"])
    op.add_column(
        "track_stream", sa.Column("skipped_count", sa.Integer(), nullable=False)
    )
    op.drop_column("track_stream", "forward_btn_count")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "track_stream",
        sa.Column(
            "forward_btn_count", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("track_stream", "skipped_count")
    op.drop_constraint(None, "spotify_track", type_="unique")
    op.drop_constraint(None, "artist", type_="unique")
    # ### end Alembic commands ###
