"""Create new table TrackStreamDay, added field highest_loop_streak in TrackStream table

Revision ID: 45380f93f7cc
Revises: 9987861e6de9
Create Date: 2025-07-21 09:17:50.818775

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "45380f93f7cc"
down_revision: Union[str, Sequence[str], None] = "9987861e6de9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "track_stream", sa.Column("highest_loop_streak", sa.Integer(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("track_stream", "highest_loop_streak")
    # ### end Alembic commands ###
