"""change on the field 'release_date' table Release type :Date -> String(20)

Revision ID: 4a5e71891f8b
Revises: 448246aa6331
Create Date: 2025-07-06 20:28:05.041737

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4a5e71891f8b"
down_revision: Union[str, Sequence[str], None] = "448246aa6331"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "release",
        "release_date",
        existing_type=sa.DATE(),
        type_=sa.String(length=20),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "release",
        "release_date",
        existing_type=sa.String(length=20),
        type_=sa.DATE(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
