"""changing field name in table TrackStreamDay loop_count -> highest_loop_streak

Revision ID: 9777873c4b09
Revises: f4a0ce06ad2a
Create Date: 2025-08-05 21:14:41.476474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9777873c4b09'
down_revision: Union[str, Sequence[str], None] = 'f4a0ce06ad2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('track_stream_day', sa.Column('highest_loop_streak', sa.Integer(), nullable=False))
    op.drop_column('track_stream_day', 'on_loop_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('track_stream_day', sa.Column('on_loop_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('track_stream_day', 'highest_loop_streak')
    # ### end Alembic commands ###
