"""Change on the field name of the table Track String(127) -> String(255)

Revision ID: 9987861e6de9
Revises: 4a5e71891f8b
Create Date: 2025-07-10 16:04:54.761163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9987861e6de9'
down_revision: Union[str, Sequence[str], None] = '4a5e71891f8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('track', 'name',
               existing_type=sa.VARCHAR(length=127),
               type_=sa.String(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('track', 'name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=127),
               existing_nullable=False)
    # ### end Alembic commands ###
