"""adding two new tables TrackMetricsSnapshot and ArtistMetricsSnapshot

Revision ID: b0ea83093de8
Revises: 9777873c4b09
Create Date: 2025-08-18 10:50:01.944385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0ea83093de8'
down_revision: Union[str, Sequence[str], None] = '9777873c4b09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist_metrics_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.Column('monthly_listeners', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artist_metrics_snapshot_artist_id'), 'artist_metrics_snapshot', ['artist_id'], unique=False)
    op.create_index(op.f('ix_artist_metrics_snapshot_collected_at'), 'artist_metrics_snapshot', ['collected_at'], unique=False)
    op.create_table('track_metrics_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.Column('playcount', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['track_id'], ['track.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_track_metrics_snapshot_collected_at'), 'track_metrics_snapshot', ['collected_at'], unique=False)
    op.create_index(op.f('ix_track_metrics_snapshot_track_id'), 'track_metrics_snapshot', ['track_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_track_metrics_snapshot_track_id'), table_name='track_metrics_snapshot')
    op.drop_index(op.f('ix_track_metrics_snapshot_collected_at'), table_name='track_metrics_snapshot')
    op.drop_table('track_metrics_snapshot')
    op.drop_index(op.f('ix_artist_metrics_snapshot_collected_at'), table_name='artist_metrics_snapshot')
    op.drop_index(op.f('ix_artist_metrics_snapshot_artist_id'), table_name='artist_metrics_snapshot')
    op.drop_table('artist_metrics_snapshot')
    # ### end Alembic commands ###
