"""making field monthly_listeners and playcount nullable in metrics table

Revision ID: ee6068863109
Revises: 4dcb98466606
Create Date: 2025-08-18 11:39:10.482146

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ee6068863109"
down_revision: Union[str, Sequence[str], None] = "4dcb98466606"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "artist_metrics_snapshot",
        "monthly_listeners",
        existing_type=sa.BIGINT(),
        nullable=True,
    )
    op.alter_column(
        "track_metrics_snapshot", "playcount", existing_type=sa.BIGINT(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "track_metrics_snapshot", "playcount", existing_type=sa.BIGINT(), nullable=False
    )
    op.alter_column(
        "artist_metrics_snapshot",
        "monthly_listeners",
        existing_type=sa.BIGINT(),
        nullable=False,
    )
    # ### end Alembic commands ###
