"""Adding new table TrackStreamDay

Revision ID: f4a0ce06ad2a
Revises: c7acef220a9b
Create Date: 2025-08-05 16:48:16.953216

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f4a0ce06ad2a"
down_revision: Union[str, Sequence[str], None] = "c7acef220a9b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "track_stream_day",
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("track_done_count", sa.Integer(), nullable=False),
        sa.Column("skipped_count", sa.Integer(), nullable=False),
        sa.Column("click_row_count", sa.Integer(), nullable=False),
        sa.Column("on_loop_count", sa.Integer(), nullable=False),
        sa.Column("total_duration_play_s", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["track_id"],
            ["track.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("track_id", "user_id", "date"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("track_stream_day")
    # ### end Alembic commands ###
